### ISSUE TITLE
[Question] Performance.

### ISSUE THREAD

**Issue by juliolitwin** [ikpil/DotRecast#2]
Hey, first I want to thank you for the great job you are doing, you even converted the demo tool!

I would like to know if you have any parameters related to performance with the original or did you not perform any yet?

There is a another project too, for performance reasons the guy decided to keep pointers (unsafe) and others things, but it's no longer an active project.

https://github.com/ryancheung/RecastSharp/tree/main

Cheers!

**Comment by ikpil** [comment]
Hello,

Regarding your question,

We are removing new float[] and replacing it with struct Vector3f to improve performance. We found some ambiguous values when checking performance with dotnet-trace, which is why we decided to make this change.

We tried to improve the project you linked to, but we faced some difficulties with memory management.

The current development direction of the DotRecast project is as follows:

We are tracking the existing recast & detour C++ code and continuously implementing it in C#.
We will write it in pure C# to ensure the productivity of debugging and operation.
If you have any further questions, please feel free to ask.
